### ISSUE TITLE
Create vrmanifest file and support registering with OpenVR applications

### ISSUE THREAD

**Issue by tjhorner** [tjhorner/WhereIsForward#7]
This is done when the user is able to register the overlay with the OpenVR runtime so that it always starts when the user enters VR.

There is very little documentation on this, but we can reverse engineer other projects to see how they did it.

OVR Advanced Settings has an installer (might be useful, because the user might need .NET Core Runtime): https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/blob/master/installer/installer.nsi

It also has this for installing the manifest: https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/blob/11c0231a6a1838fd97f7ba3aa60f54526be6c7a9/src/utils/setup.cpp#L129-L151

Just looks like we need to hit `IVRApplications::AddApplicationManifest`: https://github.com/ValveSoftware/openvr/blob/e3d37563fd0405117f035c111346f60ca12625ba/headers/openvr.h#L2396-L2401

And here's the manifest itself: https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/blob/11c0231a6a1838fd97f7ba3aa60f54526be6c7a9/src/package_files/manifest.vrmanifest

Aardvark's vrmanifest: https://github.com/aardvarkxr/aardvark/blob/master/data/aardvark.vrmanifest

OVR Toolkit's manifest:

```json
{
	"source" : "builtin",
	"applications": [{
		"app_key": "CurtisVL.OVRToolkit",
		"launch_type": "binary",
		"binary_path_windows": "OVRToolkit-AutoLaunch.exe",
		"is_dashboard_overlay": true,

		"strings": {
			"en_us": {
				"name": "OVR Toolkit",
				"description": "Desktop overlay utility for SteamVR"
			}
		}
	}]
}
```

**Comment by Cobular** [comment]
This seems finished but there's more manifests here https://github.com/LibreVR/Revive/blob/2.1.1/ReviveOverlay/app.vrmanifest https://github.com/LibreVR/Revive/blob/2.1.1/ReviveOverlay/support.vrmanifest which might be of some use eventually
